[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "newtutils"
version = "0.6.0"
description = "A collection of utility functions for common programming tasks."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

authors = [
  { name = "Anna Burova", email = "burova.anna+git@gmail.com" }
]

dependencies = [
  "colorama>=0.4.6",
]

keywords = [
  "newtutils",
  "console",
  "utility",
  "files",
  "sql",
  "network",
  "helpers",
  "validation",
  "sorting",
  "database",
  "sqlite",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
]

[project.urls]
homepage = "https://github.com/AnnaBurova/dev-newtutils"
repository = "https://github.com/AnnaBurova/dev-newtutils"
issues = "https://github.com/AnnaBurova/dev-newtutils/issues"
changelog = "https://github.com/AnnaBurova/dev-newtutils/blob/main/CHANGELOG.md"

[tool.hatch.build.targets.wheel]
packages = ["src/newtutils"]
only-packages = true

[tool.hatch.build.targets.sdist]
only-include = [
]
exclude = [
]
